services:
  postgres:
    container_name: postgres-ryo-forms
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ryoforms
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
